### ISSUE TITLE
Xacro files point to wrong DAE location

### ISSUE THREAD

**Issue by Myzhar** [westonrobot/scout_ros2#2]
Hi,
the xacro files point to a wrong DAE location:
`<mesh filename="package://scout_description/meshes/scout_v2/<file_name>.dae" />`
while only the following location exists:
`<mesh filename="package://scout_description/meshes/<file_name>.dae" />`

**Comment by cristinaluna** [comment]
Hi @Myzhar!

I fixed it on  #1 and also added the QoS settings for visualisation. It was solved on july but merged two days ago.

**Comment by cristinaluna** [comment]
@rdu-weston @hanskw-weston  you can mark this issue as closed!
