### ISSUE TITLE
URDF and meshes for Scout Mini

### ISSUE THREAD

**Issue by Myzhar** [westonrobot/scout_ros2#4]
The [scout_base](https://github.com/westonrobot/scout_ros2/tree/main/scout_base) package provides a launch file that can be used to correctly control a Scout Mini robot in ROS2, but the [scout_description](https://github.com/westonrobot/scout_ros2/tree/main/scout_description) package misses meshes and URDF (xacro) for the Scout Mini.

Is it possible to add them?

**Comment by hanskw-weston** [comment]
Added in #9
